config/routes.rb
Rails.application.routes.draw do
  get 'persons/profile', as: 'user_root'
  # get 'users/:id' => 'users#show'
  devise_scope :users do
   	get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items  do
  	get :upvote,    on: :member
  	get :expensive, on: :collection
  end
  get "admin/users_count" => "admin#users_count"
    #get ':controller(/:action(/:id))(.:format)'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	has_many :comments, as: :commentable
	
end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	#has_and_belongs_to_many :items
	has_many   :positions
	has_many   :items, through: :positions

	
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true

end

app/models/item.rb
class Item < ApplicationRecord

	validates :price,  numericality: {greater_than: 0, allow_nil: true }
	validates :price,  presence: true

	#has_and_belongs_to_many :carts

	has_many :positions
	has_many :carts, through: :positions

	has_many :comments, as: :commentable

	#belongs_to :category
#
	#after_initialize  { }
	#after_save       { }
	#after_create     { category.inc(:items_count, 1) }
	#after_update     { }
	#after_destroy    {  category.inc(:items_count, -1) }
end

app/models/order.rb
class Order < ApplicationRecord

	#belongs_to :use
	belongs_to :user, optional: true
end

app/models/position.rb
class Position < ApplicationRecord
	belongs_to :item
	belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord

	#attr_accessible :login
	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :trackable,
          :validatable
	

	has_one  :cart
	has_many :orders
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #before_action :authenticate_user!
  private

	  def render_403
	  	render file: "/public/403.html", status: 403
	  end

	  def render_404
	  	render file: "/public/404.html", status: 404
		#render text: "page not founds", status: 404
	  end

	  def check_if_admin
	  	#render text: "Access denied", status: 403 unless current_user.admin == true
		#render text: "Access denied", status: 403 unless params[:admin]
		#render_403 unless params[:admin]
	  end

	

	
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
		#attr_accessible  :name, :description, :price, :weight, :real
	
	before_filter  :find_item, only: [:show, :edit, :update, :destroy, :upvote]
	before_filter  :check_if_admin, only: [ :edit, :update, :new, :create, :destroy]
	def index
		#@items = Item.all
		@items = Item
		@items = @items.where("price >= ?", params[:price_from]) if params[:price_from]
		@items = @items.where("created_at >= ?", 1.day.ago)      if params[:today]
		@items = @items.where("vote_count >= ?", params[:votes_from])      if params[:votes_from]
		@items = @items.order("vote_count DESC", "price")
		#render text: @items.map { |i| "#{i.name}: #{i.price}"}.join("<br/>")
	end
	def expensive
		@items = Item.where("price > 1000")	
		render "index"	
	end

# /items/1 GET
	def show
		#unless
		 @item
		#render "items/show"
		#render text: "page not founds", status: 404
		#render file: "/home/admina/Документи/Ruby_Files/Project/my_store/public/404"
		#render_404
			#end
	end

#  /items/new GET
	def new
	@item = Item.new	
	end

	# /items/1/edit GET
	def edit
		#@item = Item.find(params[:id])
		
	end
	# /items POST
	def create
		@item = Item.create(item_params)
		#render text: params.inspect
		#@item = Item.create(name: params[:name], description: params[:description], price: params[:price], real: params[:real], weight: params[:weight] )
		#render  text: "#{@item.id}: #{@item.name} (#{!@item.new_record?})"
		#puts @item.errors.full_messages
		if @item.errors.empty?
			redirect_to item_path(@item)
		else
			render "new"
		end
	end

	# /items/1 PUT
	def update
		#@item = Item.find(params[:id])
		@item.update_attributes(item_params)
		if @item.errors.empty?
			flash.now[:success] = "Item successfully updated!"
			redirect_to item_path(@item)
		else
			flash.now[:error] = "You made mistakes in your form! Please correct them."
			render "edit"
		end
	end

	# /items/1 DELETE
	def destroy
		#@item = Item.find(params[:id])
		@item.destroy
		redirect_to action: "index"
	end

	def upvote
		@item.increment!(:vote_count)
		redirect_to action: :index
	end
	private

	def find_item
		#@item = Item.find(params[:id])
		@item = Item.where(id: params[:id]).first
		render_404 unless @item		
		
	end

	def item_params
		params.require(:item).permit(:price, :weight, :real, :name, :description, :image)
		
	end



end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  	@user = current_user
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper

	def urls_to_mail(s)
		s.gsub(/\s([\w\.]+@([\w]+\.)+[\w]{2,4})\s/,	'<a href="mailto:\1">\1</a></br>').html_safe		
	end

	def urls_to_images(s)
		s.gsub(/\s((http|https):\/\/.*?\.(png|jpg))\s/, '<p><img src="\1"/></p>').html_safe
		
	end

	def urls_to_links(s)
		s.gsub(/\s((http|https):\/\/.*?)\s/, '<a href="\1">\1</a></br>').html_safe

	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/items/_form.html.erb
<%= f.input :price, label: "Ціна:" %>
<%= f.input :name, label: "Назва:" %>
<%= f.input :weight, label: "Вага:" %>
<%= f.input :description, label: "Опис:" %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= simple_form_for @item do |f| %>

	<%= render partial: "form", locals: { f: f} %>
	
<p><%= f.submit "Save item" %></p>

<% end %>

app/views/items/index.html.erb
<!--
<% @items.each do |i| %>
	<P><%= link_to i.name, item_path(i)%></P>
<% end %>
-->
<h1>Items</h1>

<% if @items.empty? %>
	<b>No items in store</b>
<% else %>
<table>
	<tr>
		<th>item id</th>
		<th>Name</th>
		<th>Price</th>
		<th> </th>
		<th></th>
	</tr>

	<% @items.each do |i| %>

	<tr>
		<td><%= i.id %></td>
		<td><%= link_to i.name, item_path(i) %></td>
		<td><%= i.price %> руб.</td>
		<td><%= link_to "Edit", edit_item_path(i) %> </td>
		<td><%= link_to "Delete", i, method: :delete, data: { confirm: "Точно видалити?" } %> </td>
		<td>Рейтинг: <%= i.vote_count %>, <%= link_to "+", upvote_item_path(i) %></td>
	</tr>

	<% end %>
	<% end %>
</table>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= simple_form_for @item do |f| %>
	<%= render partial: "form", locals: { f: f} %>

<p><%= f.submit "Create item" %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if notice %>
  	<p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  	<p class="alert alert-danger"><%= alert %></p>
  <% end %>



<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<p style="color: red"><%= flash[:error] %></p>
<p style="color: green"><%= flash[:success] %></p>

  
    <%= yield %>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Profile</h1>

<table>
<tr>
<td>Your email:</td>
<td><%= @user.email%></td>
</tr>

<tr>

</tr>


</table>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/shared/_email.html.erb
<div class="email">
По всіх питанням звeртайтесь на
<script type="text/javascript"><!--
/*var aixccwp = ['i','i', '>', '@','t', 'r','<','.' ,'"','/','=','h','a','n','a','u','a','a','@','a','b','=','m','a','r','a','r']*/

a="DMGBCAGIHCGFGGDNCCGNGBGJGMHEGPDKGCHCGBGJGOHDEAGIGBHDGCHCGBGJGOHDCOHCHFCCDOGCHCGBGJGOHDEAGIGBHDGCHCGBGJGOHDCOHCHFDMCPGBDO";for(i=0;i< a.length;i++){document.write((a.charCodeAt(i)<=127)?String.fromCharCode((a.charCodeAt(i)-65)*16+(a.charCodeAt(++i)-65)):a.charAt(i))}
 // -->
</script>
<noscript>Please enable JavaScript to see email address</noscript>

</div>